title: Ben Parker # your name (or website title) here
logo: "/images/headshot2.1.jpg" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Math enthusiast, instructor, TA
  <br><br>
  <a href="https://www.linkedin.com/in/ben-parker-734378170/">LinkedIn</a> 
  <br><br>
  <a href="https://github.com/bparker9">GitHub</a>
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
